<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>login-variant</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7b1771c4-b352-4049-91aa-c09e0ae74754</testSuiteGuid>
   <testCaseLink>
      <guid>4e204c00-13fc-460c-94f6-7aed49699301</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrangeHRM/login/03 - login variant</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>97c10863-af24-4855-95a3-f75b26010c7a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/OrangeHRM/login/login-variant-db</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>97c10863-af24-4855-95a3-f75b26010c7a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>66d9a52e-abf0-4f1c-a479-496367769302</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>97c10863-af24-4855-95a3-f75b26010c7a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>a7de34ad-da12-49cd-a2d0-94c8af60045f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
